// This is raw Javascript because it's invoked from gradle, and I'm trying
// to avoid a build step for these scripts on the student machine.

import * as fs from 'fs/promises';
import * as path from 'path';

const [, , outDir, filesAsString] = process.argv;

const packageDir = ['com', 'robotcode', 'shared'];
const outputLocation = path.join(outDir, 'generated-sources', ...packageDir);

// Need to parse files
const filesNoBrackets = filesAsString.substring(1, filesAsString.length - 1);
const files = filesNoBrackets
  .split(', ')
  .filter(
    (val) =>
      val.toLocaleLowerCase().indexOf('auto') >= 0 &&
      val.toLocaleLowerCase().indexOf('const') >= 0,
  );

async function main() {

  // TODO: Finish the simple stuff up.

  // At this point, I have a 'files' array of only things that
  // include "auto" and "const". These files need to have their package
  // lines removed and their import types adjusted to be MeepMeep compatible

  // Once that's done, I could move on to extracting the robot information
  // from Technolib/RR setup code from the bot, but that's just not very
  // difficult, and doesn't change regularly, so it's probably not worth
  // the effort.

  const output = `/*
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 * !!!!!!!!!!!WARNING!!!!!!!!!!!!!
 * !!!! DO NOT EDIT THIS FILE !!!!
 * !!!!!!!!!!!WARNING!!!!!!!!!!!!!
 * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 *
 * Any edits you make will get obliterated when you build. Instead, make edits
 * to these files:
 *
 * ${files.join('\n * ')}
 *
 * and those changes will be reflected in here when you next build.
 *
 * If you're struggling to get things to compile properly, know that you should
 * not be using "fully qualified" typenames, but should only import the whole
 * types, and the build will fix them up to work for MeepMeep.
 */

package ${packageDir.join('.')};

public class TestClass {
    public static int value = 15;
}`;

  try {
    await fs.mkdir(outputLocation, { recursive: true });
  } catch (e) {
    console.error(e);
  }
  // Do we want to put the file in the 'right' directory to avoid the warning?
  await fs.writeFile(path.join(outputLocation, 'TestClass.java'), output);
}

main(outDir, files).catch(console.error);
